version: "3.8"

services:
  app:
    restart: always
    build: .
    ports:
      - 5000:${PORT}
    env_file:
      - .env
    working_dir: /home/node/app
    volumes:
      - type: bind
        source: ~/dev/TicketDesk/
        target: /backend
    command: "npm run server"
